### ISSUE TITLE
Concurrency Issue in your PassengersAPI Packet Listener

### ISSUE THREAD

**Issue by retrooper** [max1mde/PassengerAPI#1]
Greetings. A member in our discord server has reported an exception and I took the time out of my day to address it to you directly. This was the [exception](https://mclo.gs/9a3O8il) provided by the user: 
![image](https://github.com/user-attachments/assets/deca5f16-d9b0-4c1e-aef7-39f4d5c1d6f4)

In our [documentation](https://packetevents.gitbook.io/docs/creating-your-first-listener) we explain that you must be cautious when designing your packet listeners as Bukkit often limits asynchronous access:
![image](https://github.com/user-attachments/assets/9d222baa-964e-48a2-893f-1efffe39ba82)

You have two ways you can fix this. 

1. You could use our utilities to "hackily" bypass this async catcher and find entities by ID:
```java
//World may be null if you wish to search through all worlds (advised to provide a world)
World world = ...;
Entity entity = SpigotConversionUtil.getEntityById(world, entityID);
```
2. You could schedule your task onto the main thread and access the world the way Minecraft expects you to do so:
```java
Bukkit.getScheduler().runTask(plugin, () -> {
        //Your entity finding code here...
});
```
In fact, you already do so here: 
https://github.com/max1mde/PassengerAPI/blob/e68a8e75ffd4c30922c65a252f38ebed1a2ef601/src/main/java/com/maximde/passengerapi/listeners/PacketSendListener.java#L45-L56

Therefore, I'm not sure why you didn't carry this out everywhere.

**Comment by retrooper** [comment]
This can be replaced with event.getPlayer()
https://github.com/max1mde/PassengerAPI/blob/e68a8e75ffd4c30922c65a252f38ebed1a2ef601/src/main/java/com/maximde/passengerapi/listeners/PacketReceiveListener.java#L27

**Comment by maximjsx** [comment]
Thanks for reaching out!
I'm gonna fix this asap.

**Comment by maximjsx** [comment]
> This can be replaced with event.getPlayer()
> 
> https://github.com/max1mde/PassengerAPI/blob/e68a8e75ffd4c30922c65a252f38ebed1a2ef601/src/main/java/com/maximde/passengerapi/listeners/PacketReceiveListener.java#L27

Yeah I just wasn't sure if `event.getPlayer()` returns a bukkit player.

**Comment by retrooper** [comment]
In the new snapshots you don't need to explicitly cast it.
